/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mike_bland.training.testing.tomcat;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

// Tomcat must be running and the latest build deployed before running this
// test. Run the Local Tomcat run configuration first.
class StringCalculatorServletTest {
    final String BASE_URL = "http://localhost:8080/strcalc";
    final URI BASE_URI = URI.create(BASE_URL);

    @Disabled("Need to get WAR deploying successfully first.")
    @Test void helloWorldPlaceholder() throws Exception {
        HttpClient client = HttpClient.newBuilder()
                .followRedirects(HttpClient.Redirect.NORMAL)
                .build();
        HttpRequest req = HttpRequest.newBuilder()
                .uri(BASE_URI)
                .GET()
                .build();

        HttpResponse<String> resp = client.send(
                req, BodyHandlers.ofString()
        );

        assertEquals(200, resp.statusCode());
        assertEquals("Hello, World!", resp.body());
    }
}
