/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mike_bland.training.testing.tomcat;

import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.net.URI;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

// Tomcat must be running and the latest build deployed before running this
// test. Run the Local Tomcat run configuration first.
class StringCalculatorServletTest {
    static private LocalTomcatServer tomcatServer = new LocalTomcatServer();
    static private URI tomcatUri;

    @BeforeAll
    static void setUpClass() throws Exception {
       tomcatUri = tomcatServer.start();
    }

    @AfterAll
    static void tearDownClass() throws Exception {
        tomcatServer.stop();
    }

    @Test void helloWorldPlaceholder() throws Exception {
        HttpClient client = HttpClient.newBuilder()
                .followRedirects(HttpClient.Redirect.NORMAL)
                .build();
        HttpRequest req = HttpRequest.newBuilder()
                .uri(tomcatUri)
                .GET()
                .build();

        HttpResponse<String> resp = client.send(
                req, BodyHandlers.ofString()
        );

        assertEquals(200, resp.statusCode());
        assertEquals("Hello, World!", resp.body());
    }
}
