[versions]
servletVer = "6.0.0"
junitVer = "5.10.0"

[libraries]
servlet = { module = "jakarta.servlet:jakarta.servlet-api", version.ref="servletVer"}
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitVer" }
