name: Run Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: gradle

      - name: Build and test
        run: ./gradlew build --no-daemon --warning-mode all

      # Per the advice from:
      # - https://octopus.com/blog/githubactions-running-unit-tests
      - name: Post test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Java tests
          path: '**/build/test-results/test*/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true
